import React, { useEffect, useState } from "react";
import { db, formatINR } from "../lib/storage";
import QuickDownload from "../components/QuickDownload";
import EmailSendButton from "../components/EmailSendButton";
import { appsScript } from "../lib/appsScript";
import { ReceiptText } from "lucide-react";

function statusColor(status) {
  if (status === "Paid") return "bg-brand-100 text-brand-700";
  if (status === "Overdue") return "bg-red-100 text-red-600";
  return "bg-amber-100 text-amber-700";
}

function isOverdue(inv) {
  if (!inv.dueDate || inv.status === "Paid") return false;
  return new Date(inv.dueDate) < new Date(new Date().toDateString());
}

export default function Invoices() {
  const [items, setItems] = useState([]);

  useEffect(() => refresh(), []);
  function refresh() {
    const list = db.getInvoices().map((inv) => ({
      ...inv,
      status: isOverdue(inv) && inv.status !== "Paid" ? "Overdue" : inv.status,
    }));
    setItems(list);
  }

  function togglePaid(inv) {
    const updated = { ...inv, status: inv.status === "Paid" ? "Unpaid" : "Paid" };
    db.saveInvoice(updated);
    refresh();
    if (appsScript.isConfigured()) {
      appsScript
        .syncInvoice({
          id: updated.id,
          number: updated.number,
          date: updated.date,
          dueDate: updated.dueDate,
          customer: updated.customer,
          total: updated.total,
          status: updated.status,
          record: updated,
        })
        .catch((err) => console.warn("Apps Script sync failed:", err.message));
    }
  }

  return (
    <div>
      <div className="mb-6">
        <h1 className="font-display font-bold text-2xl">Invoices</h1>
        <p className="text-ink/50 text-sm">{items.length} created — generated by converting a Proforma Invoice.</p>
      </div>

      <div className="bg-white rounded-xl2 shadow-card overflow-hidden">
        <table className="w-full text-sm">
          <thead className="bg-brand-50 text-brand-700 text-xs uppercase">
            <tr>
              <th className="text-left px-4 py-3">Invoice #</th>
              <th className="text-left px-4 py-3">Date</th>
              <th className="text-left px-4 py-3">Due</th>
              <th className="text-left px-4 py-3">Customer</th>
              <th className="text-right px-4 py-3">Total</th>
              <th className="text-center px-4 py-3">Status</th>
              <th className="px-4 py-3"></th>
            </tr>
          </thead>
          <tbody>
            {items.map((inv) => (
              <tr key={inv.id} className="border-t border-ink/5 hover:bg-brand-50/40">
                <td className="px-4 py-3 font-medium flex items-center gap-2">
                  <ReceiptText size={14} className="text-brand-400" /> {inv.number}
                </td>
                <td className="px-4 py-3">{inv.date}</td>
                <td className="px-4 py-3">{inv.dueDate}</td>
                <td className="px-4 py-3">{inv.customer?.name}</td>
                <td className="px-4 py-3 text-right">{formatINR(inv.total)}</td>
                <td className="px-4 py-3 text-center">
                  <button
                    onClick={() => togglePaid(inv)}
                    className={`px-2.5 py-1 rounded-full text-xs font-semibold ${statusColor(inv.status)}`}
                  >
                    {inv.status}
                  </button>
                </td>
                <td className="px-4 py-3 text-right space-x-3 flex justify-end">
                  <QuickDownload doc={inv} type="invoice" />
                  <EmailSendButton doc={inv} type="invoice" />
                </td>
              </tr>
            ))}
            {items.length === 0 && (
              <tr>
                <td colSpan={7} className="px-4 py-10 text-center text-ink/40">
                  No invoices yet. Convert a proforma invoice first.
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>

      <p className="text-xs text-ink/40 mt-4">
        Click a status pill to mark an invoice Paid — invoices past their due date are flagged "Overdue" automatically.
        {" "}Connect email automation in Settings to get daily reminder emails sent for you on due/overdue invoices.
      </p>
    </div>
  );
}
