import React, { useEffect, useState } from "react";
import { db, formatINR } from "../lib/storage";
import DocumentBuilder from "./DocumentBuilder";
import { ArrowRight, FileCheck2 } from "lucide-react";
import QuickDownload from "../components/QuickDownload";
import EmailSendButton from "../components/EmailSendButton";

export default function Proformas() {
  const [items, setItems] = useState([]);
  const [view, setView] = useState("list");
  const [active, setActive] = useState(null);

  useEffect(() => refresh(), []);
  function refresh() {
    setItems(db.getProformas());
  }

  if (view === "convert" && active) {
    return (
      <div>
        <button onClick={() => { setView("list"); refresh(); }} className="text-sm text-ink/50 hover:text-brand-600 mb-4">
          ← Back to list
        </button>
        <DocumentBuilder type="invoice" sourceDoc={active} onSaved={refresh} />
      </div>
    );
  }

  return (
    <div>
      <div className="mb-6">
        <h1 className="font-display font-bold text-2xl">Proforma Invoices</h1>
        <p className="text-ink/50 text-sm">
          {items.length} created — generated by converting a Quotation, no manual typing needed.
        </p>
      </div>

      <div className="bg-white rounded-xl2 shadow-card overflow-hidden">
        <table className="w-full text-sm">
          <thead className="bg-brand-50 text-brand-700 text-xs uppercase">
            <tr>
              <th className="text-left px-4 py-3">Proforma #</th>
              <th className="text-left px-4 py-3">From Quote</th>
              <th className="text-left px-4 py-3">Date</th>
              <th className="text-left px-4 py-3">Customer</th>
              <th className="text-right px-4 py-3">Total</th>
              <th className="px-4 py-3"></th>
            </tr>
          </thead>
          <tbody>
            {items.map((p) => (
              <tr key={p.id} className="border-t border-ink/5 hover:bg-brand-50/40">
                <td className="px-4 py-3 font-medium flex items-center gap-2">
                  <FileCheck2 size={14} className="text-brand-400" /> {p.number}
                </td>
                <td className="px-4 py-3 text-ink/50">{p.sourceNumber || "—"}</td>
                <td className="px-4 py-3">{p.date}</td>
                <td className="px-4 py-3">{p.customer?.name}</td>
                <td className="px-4 py-3 text-right">{formatINR(p.total)}</td>
                <td className="px-4 py-3 text-right">
                  <div className="flex items-center justify-end gap-3">
                    <QuickDownload doc={p} type="proforma" />
                    <EmailSendButton doc={p} type="proforma" />
                    <button
                      onClick={() => {
                        setActive(p);
                        setView("convert");
                      }}
                      className="flex items-center gap-1 text-brand-600 text-xs font-semibold hover:text-brand-700"
                    >
                      Convert to Invoice <ArrowRight size={13} />
                    </button>
                  </div>
                </td>
              </tr>
            ))}
            {items.length === 0 && (
              <tr>
                <td colSpan={6} className="px-4 py-10 text-center text-ink/40">
                  No proforma invoices yet. Convert a quotation first.
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}
